### ISSUE TITLE
Possible to re-route the URL to the KC URL going forward?

### ISSUE THREAD

**Issue by bschrammIBM** [ibm-cloud-architecture/Learning-Kabanero-101#76]
Now that we have the KC with more content, does it makes sense to route the Learn Kab 101 URLS to the KC URL?

**Comment by bkribbs15** [comment]
We could, what does the KC cover? I have yet to see it.

**Comment by bkribbs15** [comment]
@bschrammIBM ^^

**Comment by csantanapr** [comment]
Yes @bschrammIBM we have in our backlog to compare which sections we can remove and replace with a link to the KC
For example workflows:
https://www.ibm.com/support/knowledgecenter/SSCSJL_4.1.x/guides/guides-stacks.html
- Developing with the OpenLiberty Stack
- Developing with the Eclipse Microprofile Stack
- Developing with the Node.js Express Stack
- Developing with the SpringBoot Stack
